# Generated by Django 5.2.16 on 2026-07-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nome"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255, verbose_name="conteúdo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="prazo"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="concluída"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tarefas", to="tasks.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "-created_at"],
            },
        ),
    ]
